## **常用框架工具-Numpy作业6**

<font color=red>你也可以将本案例相关的 ipynb 学习笔记分享到[ AI Gallery Notebook](https://marketplace.huaweicloud.com/markets/aihub/notebook/list/) 版块获得[成长值](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=9b8d7e7a-a150-449e-ac17-2dcf76d8b492)，分享方法请查看[此文档](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=8afec58a-b797-4bf9-acca-76ed512a3acb)。</font>

### **题目描述**
### 创建一个二维数组，其中边界值为1，其余值为0 。

提示: array[1:-1, 1:-1]

### **代码实现**
请在下面 cell 中编写代码，实现题目描述的要求。

In [2]:
import numpy as np

"""
请在此处实现代码
"""
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
