## **常用框架工具-Numpy作业7**

<font color=red>本课程未完全覆盖 Numpy 中的全部操作，欢迎你将更全面的 Numpy 学习笔记分享到[ AI Gallery Notebook](https://marketplace.huaweicloud.com/markets/aihub/notebook/list/) 版块获得[成长值](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=9b8d7e7a-a150-449e-ac17-2dcf76d8b492)，分享方法请查看[此文档](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=8afec58a-b797-4bf9-acca-76ed512a3acb)。</font>

### **题目描述**
### 对一个5x5的随机矩阵做归一化。

提示: (x - min) / (max - min)

### **代码实现**
请在下面 cell 中编写代码，实现题目描述的要求。

In [3]:
import numpy as np

"""
请在此处实现代码
"""
# 归一化公式 (x - min) / (max - min)
arr = np.random.randint(1,101, (5,5))
print("归一化前：", arr)
arr_with_normalization = (arr - arr.min()) / (arr.max() - arr.min())
print("归一化后：", arr_with_normalization)

归一化前： [[45 10 97 20 61]
 [73 56 33 82 17]
 [71 80 90  5 75]
 [84 85 17 99 47]
 [37 88 35 31 20]]
归一化后： [[0.42553191 0.05319149 0.9787234  0.15957447 0.59574468]
 [0.72340426 0.54255319 0.29787234 0.81914894 0.12765957]
 [0.70212766 0.79787234 0.90425532 0.         0.74468085]
 [0.84042553 0.85106383 0.12765957 1.         0.44680851]
 [0.34042553 0.88297872 0.31914894 0.27659574 0.15957447]]
