## **机器学习-KNN作业**

本课程未完全覆盖 KNN 的全部操作，欢迎你将更全面的 KNN 学习笔记分享到[ AI Gallery Notebook](https://marketplace.huaweicloud.com/markets/aihub/notebook/list/) 版块获得[成长值](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=9b8d7e7a-a150-449e-ac17-2dcf76d8b492)，分享方法请查看[此文档](https://marketplace.huaweicloud.com/markets/aihub/article/detail/?content_id=8afec58a-b797-4bf9-acca-76ed512a3acb)。

### **题目描述**

请你尝试修改 KNeighborsClassifier() 函数的 weights（权重） 参数的不同取值，看看该参数的修改对模型会有怎样的影响

提示：

1. 你可以在cell中执行代码"help(函数名)"来查看函数的使用方法；
2. <font color='red'>请在下文中搜索英文问号?，问号所在之处就是你需要修改代码的地方</font>；
3. 修改好代码之后，跑通整个案例代码，即可完成作业，请将完成的作业分享到AI Gallery，<font color='red'>标题以“2021实战营”为开头命名</font>；

### **代码实现**
请在下面 cell 中编写代码，实现题目描述的要求。

### 1、导入实验所需的sklearn包，导入numpy，进行矩阵计算

In [1]:
# 从sklearn 导入KNeighborsClassifier方法
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

### 2、提供简单的数据结构进行后续的KNN算法验证

In [2]:
X = np.array([[1, 1], [1, 1.5], [2, 2.5], [2.5, 3], [1.5, 1], [3, 2.5]])
y = ['A', 'A', 'B', 'B', 'A', 'B']

### 3、KNN算法的内容

根据sklearn提供的包 创建knn算法对象

n_neighbors=5           

int 型参数    knn算法中指定以最近的几个最近邻样本具有投票权，默认参数为5

algrithm='auto'           

str参数       即内部采用什么算法实现。有以下几种选择参数：

'ball_tree':球树、'kd_tree':kd树、'brute':暴力搜索、'auto':自动根据数据的类型和结构选择合适的算法。

默认情况下是‘auto’。暴力搜索就不用说了大家都知道。具体前两种树型
数据结构哪种好视情况而定。KD树是对依次对K维坐标轴，以中值切分构造
的树,每一个节点是一个超矩形，在维数小于20时效率最高

ball tree 是为了克服KD树高维失效而发明的，其构造过程是以质心
C和半径r分割样本空间，每一个节点是一个超球体。一般低维数据用
kd_tree速度快，用ball_tree相对较慢。超过20维之后的高维数据
用kd_tree效果反而不佳，而ball_tree效果要好，具体构造过程及
优劣势的理论大家有兴趣可以去具体学习。

### 4、调用KNN算法

In [5]:
model_uniform = KNeighborsClassifier(n_neighbors=4, algorithm='ball_tree', weights='uniform')  # 请在此处修改 weights 的参数值
model_distance = KNeighborsClassifier(n_neighbors=4, algorithm='ball_tree', weights='distance')
model_callable = KNeighborsClassifier(n_neighbors=4, algorithm='ball_tree', weights= lambda x:x)

### 5、训练数据

In [6]:
"""
fit 就是训练模型
fit()                     
训练函数，它是最主要的函数。接收参数只有1个，就是训练数据集，
每一行是一个样本，每一列是一个属性。它返回对象本身，即只是修
改对象内部属性，因此直接调用就可以了，后面用该对象的预测函数
取预测自然及用到了这个训练的结果。其实该函数并不是
KNeighborsClassifier这个类的方法，
而是它的父类SupervisedIntegerMixin继承下来的方法。
"""
model_uniform.fit(X, y)
model_distance.fit(X, y)
model_callable.fit(X, y)

KNeighborsClassifier(algorithm='ball_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights=<function <lambda> at 0x7f4063124ae8>)

### 6、预测结果，可以查看分类结果

In [7]:
# 预测
print(model_uniform.predict([[1.75, 1.75]]))  # 输出分类结果
print(model_distance.predict([[1.75, 1.75]]))  # 输出分类结果
print(model_callable.predict([[1.75, 1.75]]))  # 输出分类结果

print(model_uniform.predict_proba([[1.75, 1.75]]))  # 返回预测属于某标签的概率
print(model_distance.predict_proba([[1.75, 1.75]]))  # 返回预测属于某标签的概率
print(model_callable.predict_proba([[1.75, 1.75]]))  # 返回预测属于某标签的概率

print(model_uniform.score(X, y))  # 输出模型训练结果
print(model_distance.score(X, y))  # 输出模型训练结果
print(model_callable.score(X, y))  # 输出模型训练结果

['A']
['A']
['A']
[[0.75 0.25]]
[[0.73300268 0.26699732]]
[[0.76967233 0.23032767]]
1.0
1.0
0.16666666666666666
